package com.chirpit;

/**
* com/chirpit/AppConfigHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class AppConfigHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.AppConfig value = null;

  public AppConfigHolder ()
  {
  }

  public AppConfigHolder (com.chirpit.AppConfig initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.AppConfigHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.AppConfigHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.AppConfigHelper.type ();
  }

}
