package com.chirpit;


/**
* com/chirpit/AppConfig.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

/**
* Updated by idl2j
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:56 AM CEST
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "AppConfig",
    keys = {"userId"}
)
public final class AppConfig implements org.omg.CORBA.portable.IDLEntity
{
  public String userId = null;
  public String ps[] = null;
  public short history = (short)0;

  public AppConfig ()
  {
  } // ctor

  public AppConfig (String _userId, String[] _ps, short _history)
  {
    userId = _userId;
    ps = _ps;
    history = _history;
  } // ctor

} // class AppConfig
