package com.chirpit;


/**
* com/chirpit/ChirpActionKind.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public class ChirpActionKind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static com.chirpit.ChirpActionKind[] __array = new com.chirpit.ChirpActionKind [__size];

  public static final int _CHIRP_KIND = 0;
  public static final com.chirpit.ChirpActionKind CHIRP_KIND = new com.chirpit.ChirpActionKind(_CHIRP_KIND);
  public static final int _RECHIRP_KIND = 1;
  public static final com.chirpit.ChirpActionKind RECHIRP_KIND = new com.chirpit.ChirpActionKind(_RECHIRP_KIND);
  public static final int _LIKE_KIND = 2;
  public static final com.chirpit.ChirpActionKind LIKE_KIND = new com.chirpit.ChirpActionKind(_LIKE_KIND);
  public static final int _DISLIKE_KIND = 3;
  public static final com.chirpit.ChirpActionKind DISLIKE_KIND = new com.chirpit.ChirpActionKind(_DISLIKE_KIND);

  public int value ()
  {
    return __value;
  }

  public static com.chirpit.ChirpActionKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ChirpActionKind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ChirpActionKind
