package com.chirpit;


/**
* com/chirpit/ChirpActionKindHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

abstract public class ChirpActionKindHelper
{
  private static String  _id = "IDL:com/chirpit/ChirpActionKind:1.0";

  public static void insert (org.omg.CORBA.Any a, com.chirpit.ChirpActionKind that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.chirpit.ChirpActionKind extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.chirpit.ChirpActionKindHelper.id (), "ChirpActionKind", new String[] { "CHIRP_KIND", "RECHIRP_KIND", "LIKE_KIND", "DISLIKE_KIND"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.chirpit.ChirpActionKind read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.chirpit.ChirpActionKind.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.chirpit.ChirpActionKind value)
  {
    ostream.write_long (value.value ());
  }

}
