package com.chirpit;

/**
* com/chirpit/ChirpActionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class ChirpActionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.ChirpAction value = null;

  public ChirpActionHolder ()
  {
  }

  public ChirpActionHolder (com.chirpit.ChirpAction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.ChirpActionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.ChirpActionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.ChirpActionHelper.type ();
  }

}
