package com.chirpit;

/**
* com/chirpit/ChirpBodyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class ChirpBodyHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.ChirpBody value = null;

  public ChirpBodyHolder ()
  {
  }

  public ChirpBodyHolder (com.chirpit.ChirpBody initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.ChirpBodyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.ChirpBodyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.ChirpBodyHelper.type ();
  }

}
