package com.chirpit;


/**
* com/chirpit/ChirpHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class ChirpHeader implements org.omg.CORBA.portable.IDLEntity
{
  public com.chirpit.ChirpId id = null;
  public com.chirpit.Location location = null;
  public long timestamp = (long)0;
  public com.chirpit.ChirpActionKind kind = null;

  public ChirpHeader ()
  {
  } // ctor

  public ChirpHeader (com.chirpit.ChirpId _id, com.chirpit.Location _location, long _timestamp, com.chirpit.ChirpActionKind _kind)
  {
    id = _id;
    location = _location;
    timestamp = _timestamp;
    kind = _kind;
  } // ctor

} // class ChirpHeader
