package com.chirpit;


/**
* com/chirpit/ChirpBody.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class ChirpBody implements org.omg.CORBA.portable.IDLEntity
{
  private String ___chirp;
  private com.chirpit.Rechirp ___rechirp;
  private String ___luser;
  private String ___dsuser;
  private com.chirpit.ChirpActionKind __discriminator;
  private boolean __uninitialized = true;

  public ChirpBody ()
  {
  }

  public com.chirpit.ChirpActionKind discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public String chirp ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifychirp (__discriminator);
    return ___chirp;
  }

  public void chirp (String value)
  {
    __discriminator = com.chirpit.ChirpActionKind.CHIRP_KIND;
    ___chirp = value;
    __uninitialized = false;
  }

  public void chirp (com.chirpit.ChirpActionKind discriminator, String value)
  {
    verifychirp (discriminator);
    __discriminator = discriminator;
    ___chirp = value;
    __uninitialized = false;
  }

  private void verifychirp (com.chirpit.ChirpActionKind discriminator)
  {
    if (discriminator != com.chirpit.ChirpActionKind.CHIRP_KIND)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.chirpit.Rechirp rechirp ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyrechirp (__discriminator);
    return ___rechirp;
  }

  public void rechirp (com.chirpit.Rechirp value)
  {
    __discriminator = com.chirpit.ChirpActionKind.RECHIRP_KIND;
    ___rechirp = value;
    __uninitialized = false;
  }

  public void rechirp (com.chirpit.ChirpActionKind discriminator, com.chirpit.Rechirp value)
  {
    verifyrechirp (discriminator);
    __discriminator = discriminator;
    ___rechirp = value;
    __uninitialized = false;
  }

  private void verifyrechirp (com.chirpit.ChirpActionKind discriminator)
  {
    if (discriminator != com.chirpit.ChirpActionKind.RECHIRP_KIND)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String luser ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyluser (__discriminator);
    return ___luser;
  }

  public void luser (String value)
  {
    __discriminator = com.chirpit.ChirpActionKind.LIKE_KIND;
    ___luser = value;
    __uninitialized = false;
  }

  public void luser (com.chirpit.ChirpActionKind discriminator, String value)
  {
    verifyluser (discriminator);
    __discriminator = discriminator;
    ___luser = value;
    __uninitialized = false;
  }

  private void verifyluser (com.chirpit.ChirpActionKind discriminator)
  {
    if (discriminator != com.chirpit.ChirpActionKind.LIKE_KIND)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String dsuser ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifydsuser (__discriminator);
    return ___dsuser;
  }

  public void dsuser (String value)
  {
    __discriminator = com.chirpit.ChirpActionKind.DISLIKE_KIND;
    ___dsuser = value;
    __uninitialized = false;
  }

  public void dsuser (com.chirpit.ChirpActionKind discriminator, String value)
  {
    verifydsuser (discriminator);
    __discriminator = discriminator;
    ___dsuser = value;
    __uninitialized = false;
  }

  private void verifydsuser (com.chirpit.ChirpActionKind discriminator)
  {
    if (discriminator != com.chirpit.ChirpActionKind.DISLIKE_KIND)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class ChirpBody
