package com.chirpit;


/**
* com/chirpit/ChirpBodyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

abstract public class ChirpBodyHelper
{
  private static String  _id = "IDL:com/chirpit/ChirpBody:1.0";

  public static void insert (org.omg.CORBA.Any a, com.chirpit.ChirpBody that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.chirpit.ChirpBody extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = com.chirpit.ChirpActionKindHelper.type ();
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [4];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for chirp (case label CHIRP_KIND)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.chirpit.ChirpActionKindHelper.insert (_anyOf_members0, com.chirpit.ChirpActionKind.CHIRP_KIND);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[0] = new org.omg.CORBA.UnionMember (
        "chirp",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for rechirp (case label RECHIRP_KIND)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.chirpit.ChirpActionKindHelper.insert (_anyOf_members0, com.chirpit.ChirpActionKind.RECHIRP_KIND);
      _tcOf_members0 = com.chirpit.RechirpHelper.type ();
      _members0[1] = new org.omg.CORBA.UnionMember (
        "rechirp",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for luser (case label LIKE_KIND)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.chirpit.ChirpActionKindHelper.insert (_anyOf_members0, com.chirpit.ChirpActionKind.LIKE_KIND);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[2] = new org.omg.CORBA.UnionMember (
        "luser",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for dsuser (case label DISLIKE_KIND)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.chirpit.ChirpActionKindHelper.insert (_anyOf_members0, com.chirpit.ChirpActionKind.DISLIKE_KIND);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[3] = new org.omg.CORBA.UnionMember (
        "dsuser",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (com.chirpit.ChirpBodyHelper.id (), "ChirpBody", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.chirpit.ChirpBody read (org.omg.CORBA.portable.InputStream istream)
  {
    com.chirpit.ChirpBody value = new com.chirpit.ChirpBody ();
    com.chirpit.ChirpActionKind _dis0 = null;
    _dis0 = com.chirpit.ChirpActionKindHelper.read (istream);
    switch (_dis0.value ())
    {
      case com.chirpit.ChirpActionKind._CHIRP_KIND:
        String _chirp = null;
        _chirp = istream.read_string ();
        value.chirp (_chirp);
        break;
      case com.chirpit.ChirpActionKind._RECHIRP_KIND:
        com.chirpit.Rechirp _rechirp = null;
        _rechirp = com.chirpit.RechirpHelper.read (istream);
        value.rechirp (_rechirp);
        break;
      case com.chirpit.ChirpActionKind._LIKE_KIND:
        String _luser = null;
        _luser = istream.read_string ();
        value.luser (_luser);
        break;
      case com.chirpit.ChirpActionKind._DISLIKE_KIND:
        String _dsuser = null;
        _dsuser = istream.read_string ();
        value.dsuser (_dsuser);
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.chirpit.ChirpBody value)
  {
    com.chirpit.ChirpActionKindHelper.write (ostream, value.discriminator ());
    switch (value.discriminator ().value ())
    {
      case com.chirpit.ChirpActionKind._CHIRP_KIND:
        ostream.write_string (value.chirp ());
        break;
      case com.chirpit.ChirpActionKind._RECHIRP_KIND:
        com.chirpit.RechirpHelper.write (ostream, value.rechirp ());
        break;
      case com.chirpit.ChirpActionKind._LIKE_KIND:
        ostream.write_string (value.luser ());
        break;
      case com.chirpit.ChirpActionKind._DISLIKE_KIND:
        ostream.write_string (value.dsuser ());
        break;
    }
  }

}
