package com.chirpit;


/**
* com/chirpit/ChirpId.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class ChirpId implements org.omg.CORBA.portable.IDLEntity
{
  public String uid = null;
  public String cid = null;

  public ChirpId ()
  {
  } // ctor

  public ChirpId (String _uid, String _cid)
  {
    uid = _uid;
    cid = _cid;
  } // ctor

} // class ChirpId
