package com.chirpit;


/**
* com/chirpit/ChirpActionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

abstract public class ChirpActionHelper
{
  private static String  _id = "IDL:com/chirpit/ChirpAction:1.0";

  public static void insert (org.omg.CORBA.Any a, com.chirpit.ChirpAction that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.chirpit.ChirpAction extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = com.chirpit.ChirpHeaderHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "header",
            _tcOf_members0,
            null);
          _tcOf_members0 = com.chirpit.ChirpBodyHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "body",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.chirpit.ChirpActionHelper.id (), "ChirpAction", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.chirpit.ChirpAction read (org.omg.CORBA.portable.InputStream istream)
  {
    com.chirpit.ChirpAction value = new com.chirpit.ChirpAction ();
    value.header = com.chirpit.ChirpHeaderHelper.read (istream);
    value.body = com.chirpit.ChirpBodyHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.chirpit.ChirpAction value)
  {
    com.chirpit.ChirpHeaderHelper.write (ostream, value.header);
    com.chirpit.ChirpBodyHelper.write (ostream, value.body);
  }

}
