package com.chirpit;

/**
* com/chirpit/LocationKindHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class LocationKindHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.LocationKind value = null;

  public LocationKindHolder ()
  {
  }

  public LocationKindHolder (com.chirpit.LocationKind initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.LocationKindHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.LocationKindHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.LocationKindHelper.type ();
  }

}
