package com.chirpit;


/**
* com/chirpit/LocationKind.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public class LocationKind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static com.chirpit.LocationKind[] __array = new com.chirpit.LocationKind [__size];

  public static final int _SOME_LOCATION_KIND = 0;
  public static final com.chirpit.LocationKind SOME_LOCATION_KIND = new com.chirpit.LocationKind(_SOME_LOCATION_KIND);
  public static final int _NONE_KIND = 1;
  public static final com.chirpit.LocationKind NONE_KIND = new com.chirpit.LocationKind(_NONE_KIND);

  public int value ()
  {
    return __value;
  }

  public static com.chirpit.LocationKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected LocationKind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class LocationKind
