package com.chirpit;

/**
* com/chirpit/NoneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class NoneHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.None value = null;

  public NoneHolder ()
  {
  }

  public NoneHolder (com.chirpit.None initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.NoneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.NoneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.NoneHelper.type ();
  }

}
