package com.chirpit;


/**
* com/chirpit/None.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class None implements org.omg.CORBA.portable.IDLEntity
{
  public boolean value = false;

  public None ()
  {
  } // ctor

  public None (boolean _value)
  {
    value = _value;
  } // ctor

} // class None
