package com.chirpit;


/**
* com/chirpit/PartitionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class PartitionsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public PartitionsHolder ()
  {
  }

  public PartitionsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.PartitionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.PartitionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.PartitionsHelper.type ();
  }

}
