package com.chirpit;


/**
* com/chirpit/Rechirp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class Rechirp implements org.omg.CORBA.portable.IDLEntity
{
  public String chirp = null;
  public String ruser = null;

  public Rechirp ()
  {
  } // ctor

  public Rechirp (String _chirp, String _ruser)
  {
    chirp = _chirp;
    ruser = _ruser;
  } // ctor

} // class Rechirp
