package com.chirpit;

/**
* com/chirpit/RechirpHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class RechirpHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.Rechirp value = null;

  public RechirpHolder ()
  {
  }

  public RechirpHolder (com.chirpit.Rechirp initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.RechirpHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.RechirpHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.RechirpHelper.type ();
  }

}
