package com.chirpit;


/**
* com/chirpit/SomeLocation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class SomeLocation implements org.omg.CORBA.portable.IDLEntity
{
  public float longitude = (float)0;
  public float latitude = (float)0;

  public SomeLocation ()
  {
  } // ctor

  public SomeLocation (float _longitude, float _latitude)
  {
    longitude = _longitude;
    latitude = _latitude;
  } // ctor

} // class SomeLocation
