package com.chirpit;

/**
* com/chirpit/SomeLocationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class SomeLocationHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.SomeLocation value = null;

  public SomeLocationHolder ()
  {
  }

  public SomeLocationHolder (com.chirpit.SomeLocation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.SomeLocationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.SomeLocationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.SomeLocationHelper.type ();
  }

}
