package com.chirpit;


/**
* com/chirpit/UserActionKindHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

abstract public class UserActionKindHelper
{
  private static String  _id = "IDL:com/chirpit/UserActionKind:1.0";

  public static void insert (org.omg.CORBA.Any a, com.chirpit.UserActionKind that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.chirpit.UserActionKind extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.chirpit.UserActionKindHelper.id (), "UserActionKind", new String[] { "FOLLOW_KIND", "UNFOLLOW_KIND"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.chirpit.UserActionKind read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.chirpit.UserActionKind.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.chirpit.UserActionKind value)
  {
    ostream.write_long (value.value ());
  }

}
