package com.chirpit;

/**
* com/chirpit/UserActionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class UserActionHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.UserAction value = null;

  public UserActionHolder ()
  {
  }

  public UserActionHolder (com.chirpit.UserAction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.UserActionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.UserActionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.UserActionHelper.type ();
  }

}
