package com.chirpit;


/**
* com/chirpit/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

/**
* Updated by idl2j
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:56 AM CEST
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "User",
    keys = {"userId"}
)
public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String surname = null;
  public String region = null;
  public String userId = null;

  public User ()
  {
  } // ctor

  public User (String _name, String _surname, String _region, String _userId)
  {
    name = _name;
    surname = _surname;
    region = _region;
    userId = _userId;
  } // ctor

} // class User
