package com.chirpit;


/**
* com/chirpit/UserActionKind.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public class UserActionKind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static com.chirpit.UserActionKind[] __array = new com.chirpit.UserActionKind [__size];

  public static final int _FOLLOW_KIND = 0;
  public static final com.chirpit.UserActionKind FOLLOW_KIND = new com.chirpit.UserActionKind(_FOLLOW_KIND);
  public static final int _UNFOLLOW_KIND = 1;
  public static final com.chirpit.UserActionKind UNFOLLOW_KIND = new com.chirpit.UserActionKind(_UNFOLLOW_KIND);

  public int value ()
  {
    return __value;
  }

  public static com.chirpit.UserActionKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected UserActionKind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class UserActionKind
