package com.chirpit;

/**
* com/chirpit/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public com.chirpit.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (com.chirpit.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.chirpit.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.chirpit.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.chirpit.UserHelper.type ();
  }

}
