package com.chirpit;


/**
* com/chirpit/UserAction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/chirpit.idl
* Wednesday, October 8, 2014 5:01:55 AM CEST
*/

public final class UserAction implements org.omg.CORBA.portable.IDLEntity
{
  public com.chirpit.UserActionKind kind = null;
  public String fromUser = null;
  public String toUser = null;

  public UserAction ()
  {
  } // ctor

  public UserAction (com.chirpit.UserActionKind _kind, String _fromUser, String _toUser)
  {
    kind = _kind;
    fromUser = _fromUser;
    toUser = _toUser;
  } // ctor

} // class UserAction
